### ISSUE TITLE
countryName instead of countryShortCode

### ISSUE THREAD

**Issue by ottoscholten** [gehrj/vue-country-region-select#1]
I would like to have the v-model output the countryName instead of the countryShortCode, is this possible?

**Comment by gehrj** [comment]
I'll create a prop that can be passed in to allow this functionality!

**Comment by gehrj** [comment]
I have added the ability to get countryName out of the v-model. There is now a prop countryName which you can set to true. Just make sure to update topCountry and your region component to match this change if you are using those as well.

**Comment by ottoscholten** [comment]
Great, thanks!

**Comment by abdessamadely** [comment]
Great it's now working, but i can't get it to work with Region.
Can i get the full Region name also
thank you for this Plugin it's really Awesome

**Comment by gehrj** [comment]
@Abdorabi I will create this for you. I am glad you are enjoying the project. I would appreciate if you could also leave a star to help others start to find these vue components as well!

**Comment by gehrj** [comment]
@Abdorabi This ability is now added and published. It works identical to how it was working for country. the prop is regionName which is a boolean that is false by default but you can set it to true to get the region in full!

**Comment by abdessamadely** [comment]
Thanks lot bro, I'll try it again, sur i'll put a start for it :)

**Comment by hamsterbacke81** [comment]
my question though, how to use this properly? I passed it in a prop
```
<country-select
      v-model="country"
      :country="country"
      :topCountry="topCountry"
      :countryName=true
      />
```
then I got the error when I select a country:
```

[Vue warn]: Error in callback for watcher "country": "TypeError: country_region_data_data.find(...) is undefined"

found in

---> <RegionSelect> at region-select.vue
       <CountrySelectComponent>
         <MdCard>
           <StandardFromContainer> at src/container/StandardFormContainer.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:618

```

same result if I pass it like this
`      :countryName="true"`
and it breaks the region selector as well, it does not corresponds with country anymore, only shows the regions from the top country.
