### ISSUE TITLE
topCountryName method needs to  check if regionObj is null

### ISSUE THREAD

**Issue by yaodev778** [gehrj/vue-country-region-select#10]
Hi,

I've spent several hours to figure out this issue and finally found it.

The issues occurred in the method topCountryName.

    topCountryName() {
      const regionObj = regions.find(region => {
        if (this.countryName) {
          return region.countryName === this.topCountry;
        } else {
          return region.countryShortCode === this.topCountry;
        }
      });
      if (this.$i18n) {
        return this.$t(regionObj.countryName);
      }
      return regionObj.countryName;
    }
The issue came from when we set topCountry props with something like 'US' (Abbreiation) and countryName props to 'true'. then in the method topCountryName, regionObj will be set null, thus in return statement, a error will occur.
Of course, we must set definitely topCountry props with not abbreviation.
But I think this issue can happen again to other people in the future because your document wrriten in abbreviated form and people can easily add countryName props with true to get the result of full name.
so I would like you to emphasize this issue for other people to avoid that.

Hope this give some help to you!

**Comment by gehrj** [comment]
@yaodev778  I will try and create a way to determine if the user has used the abbreviation instead of the full country name in this scenario and autocorrect it for them. I think I can do this, I just need to go through the countries names and abbreviations and make sure there will not be any problems with what I have in mind.

**Comment by gehrj** [comment]
@yaodev778 I have updated the project to have a failsafe now so if the user wants to have the full country names but uses an abbreviated top country the component should fix this for them. Thanks for spending time on helping make this improvement. I would appreciate if you can leave a star to also help more people find this component!
