### ISSUE TITLE
Usage with vue-i18n should be customisable

### ISSUE THREAD

**Issue by rcarcasses** [gehrj/vue-country-region-select#13]
Hello,

Thanks for your hard work. I just found that using this library within an existing project that have `vue-i18n` support produces a huge amount of warnings like this:

![image](https://user-images.githubusercontent.com/665844/57144300-afa8dc00-6db8-11e9-80ef-6453ae7e501b.png)

By inspecting the library code I can see that indeed, if `$i18n` is defined, it tries to automatically translate every single country, and since I don't have a list of translated names of countries, then the warnings happens.

I think this behaviour should be customisable, like adding a new option `use-i18n="false"` would turn off this automatic translation, even if it can be enabled by default. 

What do you think? Thank you once more!

**Comment by gehrj** [comment]
@rcarcasses Hey thank you for finding this issue, I will make that a new option. It will be true by default, but you can set it to false if you want to disable it.

**Comment by rcarcasses** [comment]
fantastic! thanks!

**Comment by gehrj** [comment]
Should be all good to go now! made prop name use188n. Just set to false .

**Comment by rcarcasses** [comment]
Awesome! you are the best! One last thing, I wonder if you meant `i18n` instead of `118n`?

**Comment by gehrj** [comment]
@rcarcasses oh wow haha good catch ill change that

**Comment by gehrj** [comment]
@rcarcasses fixed! sorry for the delay

**Comment by rcarcasses** [comment]
awesome man, keep doing a great job!
