### ISSUE TITLE
selector break when pass countryName

### ISSUE THREAD

**Issue by hamsterbacke81** [gehrj/vue-country-region-select#14]
my question  how to use countryName properly? I passed it in a prop

```
<country-select
      v-model="country"
      :country="country"
      topCountry="DE"
      :countryName=true
      />
```

then I got the error when I select a country:

```
[Vue warn]: Error in callback for watcher "country": "TypeError: country_region_data_data.find(...) is undefined"

found in

---> <RegionSelect> at region-select.vue
       <CountrySelectComponent>
         <MdCard>
           <StandardFromContainer> at src/container/StandardFormContainer.vue
             <App> at src/App.vue
               <Root> vue.runtime.esm.js:618
```

same result if I pass it like this
`:countryName="true"`
and it breaks the region selector as well, it does not corresponds with country anymore, only shows the regions from the US.
I read in other issure that this may caused by the parameter topCountry being an abbreviation, so I changed this too (topCountry="Germany"), still got the same error though

**Comment by hamsterbacke81** [comment]
just fount out that if I set countryName=true in country-selector, I have to set countryName=true in region selector too, or it will break. In the documentation it didn't mention that set countryName will be mandatory if this is set in country-selector. It would be nice if you could change it. Thx a lot!

**Comment by gehrj** [comment]
@hamsterbacke81 I will make this more clear in the docs
