### ISSUE TITLE
v-model only pre-populating country and not region

### ISSUE THREAD

**Issue by DeeRock94** [gehrj/vue-country-region-select#15]
Hi there,

Everything is working perfectly but when I v-model the data to both of the components, it appears that the Country one correctly selects the existing country a user may have but the county/region one shows as 'Please select a region' instead of also pre-populating this information if we have it.

`                    <country-select class="form-control" v-model="details.country" :countryName="true" :country="details.country" topCountry="GB" />

                    <region-select class="form-control" v-model="details.county" :country="details.country" :countryName="true" :regionName="true" />
`

Both pieces of data are exactly matching the values held in the dropdown so I can't work out what might be wrong?

**Comment by DeeRock94** [comment]
![image](https://user-images.githubusercontent.com/15680888/60818049-c68ef480-a194-11e9-9054-5dca70be786b.png)

Image above displays the Country being pre-populated (from the DB) and the Region isn't pre-populated. I've also echoed out the held data above the dropdown to demonstrate it matches exactly what is held within the country JS file.

**Comment by gehrj** [comment]
@DeeRock94 is this all happening on load or are you using a button or something to populate the values after the page has loaded? When I try and preset both of those values in my data I am not seeing this issue, but we did have something similar occur before so maybe a little more information on when the data is being populated can help.

**Comment by gehrj** [comment]
This is what I am entering and what I am getting in a very basic setup.

![Screen Shot 2019-07-08 at 9 44 22 AM](https://user-images.githubusercontent.com/26335236/60819507-51f09180-a165-11e9-8d7f-2de5cd6beea8.png)


<img width="1073" alt="Screen Shot 2019-07-08 at 9 43 55 AM" src="https://user-images.githubusercontent.com/26335236/60819524-587f0900-a165-11e9-8181-aee6574efc31.png">

**Comment by gehrj** [comment]
actually with further looking at what you have posted I would try adding :region="details.county" to your region select and see if this fixes your issue?

**Comment by DeeRock94** [comment]
> actually with further looking at what you have posted I would try adding :region="details.county" to your region select and see if this fixes your issue?

Absolutely nailed it on the head! What a silly issue, I actually removed :region for testing purposes a few hours ago and must have completely forgotten to re-add it. You've fixed the issue and I greatly appreciate your time with this today! Schoolboy error from me

**Comment by gehrj** [comment]
No Problem, glad we could get it fixed!
