### ISSUE TITLE
Update data.js

### ISSUE THREAD

**Issue by bobbygrossmann** [gehrj/vue-country-region-select#18]
Hi cant you just update data.js from https://github.com/country-regions/country-region-data/blob/master/data.js .  It has all new changes including swedish regions.

After update how do i get the new dist ? i did npm run update /removed and tried install but i see it only installs dist/vueCountryRegionSelect.umd.min.js

**Comment by gehrj** [comment]
the project was originally using that data as a dependency but at one point it was requested that the data be in the project here so it allowed more specific customizations. I think i will pull in thier updated data set and overwrite the one we have and start fresh from that point, if it has the current changes you just made then everything should still run fine. Thanks for this information, I'm going to try and make the change now.

**Comment by gehrj** [comment]
okay @bobbygrossmann everything should be updated and working now! Feel free to make changes to data if something you need is missing but it looks like the region you had added is included in this update!
