### ISSUE TITLE
Registering Component

### ISSUE THREAD

**Issue by dundas** [gehrj/vue-country-region-select#19]
Hi there - thanks for the package. 

I'm getting an error about registering the component. 

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Unknown custom element: <region-select> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Profile> at src/components/ProfileBusinessCreate.vue
       <VContent>
         <VApp>
           <App> at src/components/layouts/AppLayout.vue
             <VApp>
               <App> at src/App.vue
                 <Root>
```

How do I register it correctly? Thanks!

**Comment by gehrj** [comment]
@dundas are you running

`import vueCountryRegionSelect from 'vue-country-region-select'
Vue.use(vueCountryRegionSelect)`

somewhere in your vue app?

**Comment by acpierc3** [comment]
I just had this same issue, fixed it by moving `Vue.use(vueCountryRegionSelect`) before my `new Vue({}).mount(app)` declaration

**Comment by gehrj** [comment]
@acpierc3 Thank you, I will make it more clear in the README file that this needs to be done before mounting the vue app

**Comment by dundas** [comment]
Thanks I will try this!
