### ISSUE TITLE
Disable Placeholder

### ISSUE THREAD

**Issue by lonnylot** [gehrj/vue-country-region-select#25]
The placeholder element is selectable. Disable it so it is no longer selectable and only informational.

**Comment by gehrj** [comment]
I can make an option for this, I do not want to make this the default feature as our own project wants it to be a selectable field.

**Comment by gehrj** [comment]
@lonnylot this is now added as a prop you can turn on, the usage is detailed in the readme

**Comment by lonnylot** [comment]
👍LGTM thanks
