### ISSUE TITLE
[Nice to have] - Removing Placeholder

### ISSUE THREAD

**Issue by Marfru** [gehrj/vue-country-region-select#27]
Hey @gehrj ,

Thanks for the latest update concercing disabling the **placeholder**, currently using it at my company.

I was wondering if you could make an extra option besides Disabling the placeholder.

Would it be possible to create a `'RemovePlaceholder'` props where the placeholder is completely deleted if there is no content in the dropdown.

Cheers, and have a good weekend! 🍻

**Comment by gehrj** [comment]
@Marfru sure I'll add this in.

**Comment by gehrj** [comment]
@Marfru it's done, If you are enjoying the project I always appreciate stars to attract more users!
