### ISSUE TITLE
country-select not working but region-select is?

### ISSUE THREAD

**Issue by flyrdm** [gehrj/vue-country-region-select#3]
I am trying to get a simple demo of your component working but I can't seem to 
get country-select to work. I noticed there are differences in the src code for
each. region-select uses a mounted() method and country-select does not.
Was this broken in the last commit when whitelist/blacklist functionality was added?

**Comment by gehrj** [comment]
Hey @flyrdm  can you  describe what you are doing in more detail? Setting it up as shown in the Read.me file seems to  be working fine.

**Comment by gehrj** [comment]
Going to assume this issue has been resolved locally.
