### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by 2O23** [gehrj/vue-country-region-select#30]

**Comment by gehrj** [comment]
@4o4forbidden  are you setting this to true for both country and region component? When setting countryName to true on the country component you must also set it to true on the region component to have them stay in sync.

**Comment by 4o4forbidden** [comment]
Hello sir ! Thanks for your reply, yeah tha'ts exactly what i did, i put true on both and just after that the problem has appeared !

Thanks !

**Comment by zahidmiah** [comment]
@4o4forbidden set the property in this way country-Name="true"

**Comment by 4o4forbidden** [comment]
Thanks i will give it a try !

**Comment by 4o4forbidden** [comment]
Thanks for your reply @zahidmiah  ! but still the same thing ! always giving the 2 letters form name

**Comment by gehrj** [comment]
@4o4forbidden can you share how you are using this?

**Comment by gehrj** [comment]
@4o4forbidden something similar to how the individual in #26 shared their code via sandbox would be the best

**Comment by 4o4forbidden** [comment]
@gehrj  everything is working good here ! except when i turn the countryName to true 
the countryName now returns the country in full letters but the regions list in no more updating to the selected country !

**Comment by Elgayar** [comment]
@4o4forbidden If you do it that way, it should definitely work, if it doesn't please share your code.
You should also double-check that you are setting `:country="country"` in the `region-select` component, to inform it of the chosen country.

`<country-select
                v-model="country"
                :countryName="true"
                :country="country"
              />`

`<region-select
                v-model="region"
                :countryName="true"
                :country="country"
                :region="region"
              />`
