### ISSUE TITLE
Default Country

### ISSUE THREAD

**Issue by Elgayar** [gehrj/vue-country-region-select#41]
I am wondering if a feature of setting a default country for the country-select component is possible.

**Comment by gehrj** [comment]
@Elgayar I believe this is covered by the topCountry option. this should put your country of choice as the first option. If you are asking about having it auto selected this can be done by setting the value where you are storing country to whatever value you want ahead of time if my memory is correct.

**Comment by Elgayar** [comment]
@gehrj yes that works, thanks for your help!
