### ISSUE TITLE
Vue imported more than once

### ISSUE THREAD

**Issue by jsancho-gpl** [gehrj/vue-country-region-select#5]
When using CountrySelect I can see warnings like `[Vue warn]: $attrs is readonly.` and `[Vue warn]: $listeners is readonly.` in the console. This is due to Vue imported in the library, so it collides with Vue being imported in my app.

**Comment by gehrj** [comment]
@jsancho-gpl are you getting this same error if index.vue is reverted back to how it originally was. I have been unable to replicate this error and would prefer not having to import an install function as before this was handled automatically with import.

**Comment by gehrj** [comment]
@jsancho-gpl Thanks for the fix! I would appreciate if you left a star so others can find this project in the future.
