### ISSUE TITLE
How to use this component with vee-validate

### ISSUE THREAD

**Issue by R00118189** [gehrj/vue-country-region-select#8]
How to use this component with vee-validate?
```<country-select className="form-control" name="country" id="country" v-validate="'required'" v-model="formData.country" :country="formData.country" :class="errors.has('country') ? 'is-invalid': ''" />```

![image](https://user-images.githubusercontent.com/6721357/54499748-270bd480-490d-11e9-87f0-13558c3a7eae.png)

**Comment by gehrj** [comment]
@R00118189 My project is setup slightly different but v-validate should be working. I will share how I am using it and hopefully it helps.
<img width="1131" alt="Screen Shot 2019-03-17 at 9 50 45 PM" src="https://user-images.githubusercontent.com/26335236/54503787-c8d7f500-48fe-11e9-8f95-88fd23dbbd33.png">

**Comment by gehrj** [comment]
I just changed the code to more closely mimic what you are doing and still can't seem to reproduce, If the error persists can you please provide some more context?
<img width="1249" alt="Screen Shot 2019-03-17 at 9 57 52 PM" src="https://user-images.githubusercontent.com/26335236/54504029-d9d53600-48ff-11e9-907f-f662544dd53f.png">

**Comment by R00118189** [comment]
Thank you, after the last compilation, error seems to be gone, please close this issue then.

**Comment by jay8t6** [comment]
@gehrj I have the same problem, it validates correctly, but then when I run validateAll() before submit, it throws an error on country and region field. Any idea why?

**Comment by jay8t6** [comment]
I can confirm that this behavior only occurs when the component is within a v-for, any help is greatly appreciated, @gehrj

**Comment by gehrj** [comment]
@jay8t6 Can you send over how you are getting this error so I can take a better look . I am not able to replicate this

**Comment by jay8t6** [comment]
@gehrj  Here's what VeeValidate's documentation says:
Must emit an input event whenever the value changes. - **This is happening**
Should have a value and name getters define in the components $_veeValidate ctor options alternatively it can use the data-vv-name as a fallback for the name prop. - **I dont see the getters for value and name. Could this be it?**

See here: https://baianat.github.io/vee-validate/examples/custom-component.html

**Comment by jay8t6** [comment]
Do you have a sample jsfiddle with veevalidate that I can fork? So I can show you what is happening.

**Comment by jay8t6** [comment]
@gehrj just tested it locally, that seems to be the problem, not defining the name and value getters in the component, Im gonna submit a PR if thats ok with you.
